### ISSUE TITLE
error

### ISSUE THREAD

**Issue by albergmac** [fpcorso/wordpress-health-check#32]
Hi. MyWordpress Health Check is showing an error of the bottom of the front end pages:
Fatal error: Call to undefined function wphc_get_total_checks() in /home/gsrne/public_html/gsrne-live/wp-content/plugins/my-wp-health-check/mlw_health_check.php on line 71
It is also not allowing me to get to my normally visible from the front end when logged in admin editing menu at the top of the page. Works fine when I disable the plugin. Any ideas for how to fix? Thanks for an otherwise great plugin -ab

**Comment by fpcorso** [comment]
Oh wow @albergmac. I had the files being included only when in admin and the file with the function causing the error is not being included when viewed from the front end when viewed as the admin. I'll have to get a fix out shortly.

**Comment by fpcorso** [comment]
Hey @albergmac I just fixed this bug and created a new release (1.3.1)  over on the [Releases](https://github.com/fpcorso/wordpress-health-check/releases) page. I am not able to update WordPress.org version until later tonight.

Thanks again for reporting this!

**Comment by albergmac** [comment]
Hi. Looks like it's working again, and not throwing the error. Thanks for the quick fix. -ab
