### ISSUE TITLE
Email template to send to web host if PHP/MySQL checks fail

### ISSUE THREAD

**Issue by nickcernis** [fpcorso/wordpress-health-check#35]
Suggest presenting an email template if MySQL or PHP health checks fail. e.g.

> Your PHP/MySQL version is no longer receiving security updates.  [Email your host today].

The link would present an email to be used as a starting point:

> Hello
> 
> My WordPress installation at [site-url] is running on [PHP x/MySQL x], an insecure version.
> 
> How do I update to the latest version of [PHP/MySQL]?
> 
> Kind regards
> 
> [firstname] [lastname]

We could perhaps even look up hostnames to match known support addresses for common hosts, then present the email as a form to fill in and send straight away.

**Comment by fpcorso** [comment]
Hey @nickcernis !

Thanks for the suggestion. I can see how a prefilled email template would be useful. Especially to users who are not familiar with PHP or MySQL at all. I want to start working on the next update next week and will try to get to this in that update.

Thanks for the feedback!

**Comment by fpcorso** [comment]
For now, we are linking the relevant checks to articles about PHP and how to update it. We will re-evaluate the possibility of adding more streamlined templates in the future.

Closing for now.
