### ISSUE TITLE
Add external url to get health check

### ISSUE THREAD

**Issue by pablodgonzalez** [fpcorso/wordpress-health-check#46]
Hi, it would be great if the plugin set up an URL for external health check. It is great for automation.

**Comment by fpcorso** [comment]
Hey @pablodgonzalez!

This sounds interesting. Can you elaborate a little on the usage here so I can look into the best way to build this out?

**Comment by pablodgonzalez** [comment]
Hi @fpcorso I will try to explain my idea.
I'm thinking in monitoring automation, now I can only check if a site is online, responding and with what performance.
What if we could check if the WP version is not updated or themes, plugins, etc?
All things that this plugin check, we could read that from another system for send alerts and actions, including proactive alerts.
Thinking some features:
would it have api keys for access auth to third parties software?
would it have an external page (with a simple list and status)?
would it have the same url with parameters to change output (ex: ?json ?xml)
would it return different http codes according its result? (ex: 200->OK 409->warning, 418->poor performance, 404->down, 4xx->other custom codes).
I hope I have been clear.
Greetings!

**Comment by nadnoslen** [comment]
I just need a simple heath check URL for load balancing.

In my Rails world I have this: https://github.com/ianheggie/health_check

**Comment by fpcorso** [comment]
Ah! @nadnoslen that is an interesting use case. I haven't had a chance to work too much on this free plugin as work has been hectic that last several months. Hoping to have some time later this month to add some new features. This one seems to be one asked by quite a few users so I will try to get this one built first.

**Comment by fpcorso** [comment]
The initial version of a new REST API for this plugin was released with the 1.6.0 version!
