### ISSUE TITLE
WordPress Plugin Missing File

### ISSUE THREAD

**Issue by LeoNelson** [fpcorso/wordpress-health-check#8]
Can you expand the health check plugin to also validate if a plugin has all the right files? For example, let's say I accidentally left out a file such as readme.txt from a plugin, the health check would be able to validate that the installed plugin is missing a specific file.

**Comment by fpcorso** [comment]
@LeoNelson Hmmm... I like that idea. However, this plugin is more for quick security/update checks so I don't think it quite fits here. My other plugin, [WordPress Developer Toolkit](https://wordpress.org/plugins/wp-developer-toolkit/), which is slowly being built for plugin developers may make more sense. If not, it is a good idea for a stand alone plugin.

Though, now that I am typing that, it would make sense for the Health Check to simply check all plugins and themes for necessary files maybe (?).

Let me ponder it over and see where it makes sense and then I'll work on it. Great suggestion!

**Comment by fpcorso** [comment]
This issue doesn't quite fit the scope of this plugin currently. I am going to close this for now.
